name: ADA Payments Image

on:
  push:
    branches:
      - "main"

jobs:
  base-layer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/txpipe/ada-payments-starter-kit,ghcr.io/txpipe/ada-payments-starter-kit:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
